######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 13 22:44:33 2019
######################################################################

CONFIG+=console
TEMPLATE = app
TARGET = 
DEPENDPATH += d:\dropboxRIT\ravvenlab\github\ravven-qt\desktop\helloWorld
INCLUDEPATH += .

# Input
SOURCES += main.cpp
